### ISSUE TITLE
Migrate the AWS native reference architecture on the core components

### ISSUE THREAD

**Issue by vgkowski** [aws-samples/aws-analytics-reference-architecture#158]
The current version of the AWS native reference architecture is using L1 and L2 Constructs from AWS CDK. The objective is to migrate part of the batch module of the reference architecture on L3 Constructs from core components including:

- DataLakeStorage
- DataLakeCatalog
- DataGenerator

This would simplify the maintenance of the reference architecture as it will automatically benefit from new L3 Constructs versions and features.

**Comment by vgkowski** [comment]
1. DataLakeCatalog can replace 3 of the 4 databases
2. Same for DataLakeStorage
3. The 3 buckets should be replaced by the DataLakeStorage ones. The current version is using a custom resource to automatically empty the bucket on deletion but it's now a [native feature of the S3 bucket construct](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.Bucket.html#autodeleteobjects). The intelligent tiering is replaced by a manual tiering (with defaults) more suited to data lake hot/cold pattern.
4. Batch data generator should be replaced by the DataGenerator but there is currently a blocker for a drop-in replacement. The data files don't contain the column names header anymore so it impacts the batch pipeline. Let's keep it as-is for now waiting for DataGenerator improvement

**Comment by ijemmy** [comment]
Ok, I will migrate only `DataLakeCatalog` and `DataLakeStorage` for now.

**Comment by ijemmy** [comment]
Changes are in PR #166
