### ISSUE TITLE
Change NotebookPlatform from a nested stack to a construct

### ISSUE THREAD

**Issue by vgkowski** [aws-samples/aws-analytics-reference-architecture#332]
Currently, NotebookPlatform extends NestedStack to ensure we doesn't reach the 500 resources limit in one Cloud Formation stack. Because of recent optimizations on the constructs, we can now extend Construct and let the consumer decide to deploy in a nested stack or not. Additionally, it would solve the issue with documentation where the NestedStack `exportValue` function breaks the entire lib documentation.

**Comment by lmouhib** [comment]
Issue solved as part of commit @9312675, documentation is live.
