### ISSUE TITLE
LfS3Location construct not compatible with cross account bucket

### ISSUE THREAD

**Issue by vgkowski** [aws-samples/aws-analytics-reference-architecture#361]
The LfS3Location requires a Bucket object and is using `grantReadWrite` to authorize the LakeFormation role to access data. This requires the bucket to be managed in the same CDK stack and so does not work in cross account setup.

We need to refactor the interface to an S3Location and an IKey (the KMS key used for the bucket encryption) and then create IAM permissions manually (not using the grantReadWrite)

**Comment by flochaz** [comment]
Custom resource ?
