### ISSUE TITLE
Multiple managed endpoints failing

### ISSUE THREAD

**Issue by alexvt-amz** [aws-samples/aws-analytics-reference-architecture#491]
First managed option is created using "tooling" EKS managed node group which is amd64 based, however additinal managed endpoints are provisioned using "shared-0" EKS managed group which is arm640-based which is casing JEG to fail provisioning. 

`Warning Failed    7m25s (x2 over 7m41s)  kubelet      Failed to pull image “[755674844232.dkr.ecr.us-east-1.amazonaws.com/notebook-jeg/emr-6.7.0:latest](http://755674844232.dkr.ecr.us-east-1.amazonaws.com/notebook-jeg/emr-6.7.0:latest)”: rpc error: code = Unknown desc = no matching manifest for linux/arm64/v8 in the manifest list entries
 Normal  BackOff   2m36s (x22 over 7m40s) kubelet      Back-off pulling image “[755674844232.dkr.ecr.us-east-1.amazonaws.com/notebook-jeg/emr-6.7.0:latest](http://755674844232.dkr.ecr.us-east-1.amazonaws.com/notebook-jeg/emr-6.7.0:latest)”`

**Comment by vgkowski** [comment]
solved by #526
