### ISSUE TITLE
Create the construct for all the major flow in Data Mesh 1/Register Data Product 2/ Request Data product 3/Approve/Deny Request

### ISSUE THREAD

**Issue by mohade09** [aws-samples/aws-analytics-reference-architecture#579]
Without the need of an UI , can ARA provide all the building blocks to build data mesh in a headless fashion

**Comment by vgkowski** [comment]
With Amazon DataZone in preview, we are prioritizing it for data mesh implementation except you have a clear use case for the existing constructs

**Comment by taabrcr** [comment]
thanks for this update @vgkowski , do you have any ETA when this is going to be available in DSF? :)
